image: python:3.10-bullseye

stages:
  - test

variables:
  HEADLESS: "true"

before_script:
  - apt-get update
  - apt-get install -y wget gnupg unzip
  - wget -q -O /usr/share/keyrings/google-linux-signing-key.asc https://dl.google.com/linux/linux_signing_key.pub
  - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-key.asc] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
  - apt-get update
  - apt-get install -y google-chrome-stable
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

ui-tests:
  stage: test
  script:
    - pytest -m ui -n auto --alluredir=allure-results
  artifacts:
    when: always
    paths:
      - allure-results/
